#these are all the helpers that don't need to be tied to a room in their name
# v1.2

# These are only just the optional inpus here, suggestion to only just
# copy the inputs from this example below.

##
##EXAMPLE YAML FOR AUTOMATION
##
# alias: roomexample_with_bp
# description: ""
# use_blueprint:
#   path: Jeffreyjelly/JJs_light_ctrl_w_helpers.yaml
#   input:
#     in_num_dim_amt: input_number.in_num_dim_amt
#     in_num_transition_time: input_number.in_num_transition_time_norm
#     in_num_transition_time_fast: input_number.in_num_transition_time_fast
#     in_datetime_day_time: input_datetime.in_datetime_day
#     in_datetime_night_time: input_datetime.in_datetime_night
#

#input_numbers
input_number:
  in_num_dim_amt:
    name: in num dim amount
    min: 0
    max: 255
    step: 1
    mode: slider
    unit_of_measurement: "dim amount"
    icon: mdi:debug-step-into
  in_num_transition_time_norm:
    name: in num transition time norm
    min: 0
    max: 10
    #removed inital because every time HA reset it seemed to put it back to that number
    # initial: 3
    step: 1
    mode: slider
    unit_of_measurement: seconds
    icon: mdi:transition
  in_num_transition_time_fast:
    name: in num transition time fast
    min: 0
    max: 3
    #removed inital because every time HA reset it seemed to put it back to that number
    # initial: 1
    step: 1
    mode: slider
    unit_of_measurement: seconds
    icon: mdi:transition

#input_datetime
input_datetime:
  in_datetime_day:
    name: in datetime day
    has_date: false
    has_time: true
    #removed inital because every time HA reset it seemed to put it back to that number
    # initial: "5:15"
    icon: mdi:sun-clock-outline
  in_datetime_night:
    name: in datetime night
    has_date: false
    has_time: true
    #removed inital because every time HA reset it seemed to put it back to that number
    # initial: "00:00"
    icon: mdi:lightbulb-night-outline